# Generated by Django 5.2 on 2025-04-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usrReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=25, unique=True)),
                ('paswd', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
