# Generated by Django 5.2 on 2025-04-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userReg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usrreg',
            old_name='paswd',
            new_name='password',
        ),
    ]
